[global]
  server role = standalone server
  server min protocol = SMB3_11
  server max protocol = SMB3_11
  smb encrypt = required
  map to guest = Never
  logging = stdout
  log level = 1
[media]
  path = /srv/media
  read only = no
  valid users = media
  force user = media
